name: Node.js CI

on:
  workflow_dispatch:

jobs:
  call-ci-workflow:
    uses: nivi30/central-workflow/.github/workflows/non-node-prod.yml@main
    with:
      node-version: 14
      npm_command: build_npm

