name: Node.js CI

on:
  workflow_dispatch:

jobs:
  call-ci-workflow:
    uses: nivi30/central-workflow/.github/workflows/non-node-prod.yml@main
    with:
      node-version: 14
      npm_command: build_npm
  build-dev:
    runs-on: ubuntu-latest
    steps:
    - name: artifact upload
      uses: actions/upload-artifact@v2
      with:
        name: node
        path: ./
      
      
    
